### ISSUE TITLE
Agenda

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-tutorial-agu-2018#1]
We currently have the following agenda as shown on the AGU website:

0830-0900: Introduction to Pangeo Project and Software Ecosystem
0900-1030: Hands-on interactive tutorial of xarray
1030-1045: Break
1045-1200: Hands-on interactive tutorial of dask
1200-1230: Tutorial for how to deploy your own Pangeo platform on cloud or HPC computing resources

But, on our Medium blog, we listed this agenda: 

8:00–8:30: Welcome and introductions
8:45–9:30: Introduction to xarray
9:30–10:15: Introduction to Dask
10:15–10:30: Break
10:30–12:00: Example applications in hydrology and oceanography
12:00–12:20: Adapting Pangeo for your own use case

So, some things to sort out. What is the agenda we really want and who's going to take the lead on specific sections?

cc @rabernat and @scottyhq

**Comment by jhamman** [comment]
I'll suggest we have three example applications - 30 minutes each

1. Ryan - Oceanography
1. Joe - Hydrology/climate
1. Scott - Remote sensing

**Comment by rabernat** [comment]
I like the medium blog agenda more. The only thing that prevents us from following that is the start time. If the official start time is 8:30, we will have to go with that.

What about:
8:30 - 8:45: Intro (all)
8:45 - 9:30: Xarray (Ryan?)
9:30 - 10:45: Dask (Joe?)
10:15 - 10:30: -- Break --
10:30 - 11:00: Remote Sensing Example (Scott)
11:00 - 11:30: Hydroclimate Example (Joe)
11:30 - 12:00: Oceanography Example (Ryan)
12:00 - 12:30: Building your own infrastructure (Joe?)

I somewhat selfishly volunteered myself for the xarray part because I have recently developed a bunch of intro-level material on xarray for my course:
https://rabernat.github.io/research_computing_2018/tag/xarray.html
(source here: https://github.com/rabernat/research_computing_2018/tree/master/content)

**Comment by scottyhq** [comment]
Sounds good to me! Thanks for putting the repository together Joe - for the example applications/notebooks, are we planning to lump them all this repo to launch from the same binder button?

**Comment by rabernat** [comment]
Also, to be clear, I'm totally happy to switch up any of what I proposed above. I'd be happy to give the dask part if--Joe--you prefer to do xarray.

**Comment by jhamman** [comment]
Happy to do the dask array part. I will probably start this with a high-level xarray-dask-kubernetes example, then talk about dask array, dask graphs, and finally dask delayed. I will probably also cover deploying dask on local, HPC, and cloud resources.

**Comment by jhamman** [comment]
@scottyhq - yes, I was thinking all the same repo/binder.

Also, what do we want to cover in the building your own infrastructure piece?

**Comment by scottyhq** [comment]
With only 30 minutes, I think a demo of pangeo-cookiecutter would be highly useful for participants. I'm happy to do that.

If people want to deploy their own pangeo the best we can do in 30 minutes is probably just give a really high level overview and highlight key guides. Some time for Q&A would be good since I suspect this will be a firehose morning for many in the room.

**Comment by rabernat** [comment]
I'm wondering what sort of prerequisites we can assume here. We did not list any. It would be nice to assume people know numpy, but this may not be the case.
